[package]
name = "dummy-redis-server"
version = "0.1.0"
edition = "2024"

[dependencies]
atoi = "2.0.0"
bytes = "1.10.1"
clap = "4.5.47"
tokio = { version = "1.47.1", features = ["io-util", "macros", "net", "rt", "rt-multi-thread", "signal", "sync", "time"] }
